version: '3.9'

services:
  db:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: twodo-db
    ports:
      - '4321:5432'
  server:
    build: .
    depends_on:
      - db
    ports:
      - '8000:8080'